[package]
name = "utf8-parser"
version = "0.0.2"
edition = "2021"
license = "MIT or APACHE-2.0"
rust-version = "1.60"

[features]
default-feature = ["std"]
std = []

[dependencies]

[dev-dependencies]
rand = "0.8"
