[package]
name = "utf8-parser"
version = "0.0.1"
edition = "2021"
license = "MIT or APACHE-2.0"
rust-version = "1.74"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints.rust]
missing_docs = "warn"
unsafe_code = "forbid"

[features]
default-feature = []
std = []

[dependencies]

[dev-dependencies]
rand = "0.8.5"
