---
name: Markdown CI

# yamllint disable-line rule:truthy
on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Clone dagan-utils
        run: git clone https://github.com/Property404/dagan-utils ../dagan-utils
      - name: Lint README
        run: ../dagan-utils/bin/wslint -- $(find . -name '*.md')
